name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clean buildozer cache
      run: |
        rm -rf ~/.buildozer
        rm -rf .buildozer

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-17-jdk unzip zip wget git
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer==1.5.0 "python-for-android==2024.1.21" cython

    - name: Install Android SDK & build-tools 33.0.0
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $HOME/cmdline-tools
        mkdir -p $HOME/android-sdk/cmdline-tools/latest
        mv $HOME/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/android-sdk

    - name: Check aidl existence
      run: |
        ls -l $HOME/android-sdk/build-tools/33.0.0/aidl || (echo "aidl not found!" && exit 1)

    - name: Build APK
      shell: bash
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROIDSDK=$HOME/android-sdk
        export PATH=$HOME/android-sdk/build-tools/33.0.0:$PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
